# MEMO：現在、Blueprintとの接続を切っているので、このファイルは利用していない
# MEMO：参照（：https://dashboard.render.com/blueprint/exs-cnslcqed3nmc73apc1o0/settings）

databases:
  - name: tentsauna_app
    databaseName: tentsauna_app
    user: tentsauna
    region: singapore

services:
  - type: web
    name: tentsauna
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: ENV['DATABASE_URL']
        fromDatabase:
          name: tentsauna_app
          property: connectionString
      - key: ENV['RAILS_MASTER_KEY']
        sync: false # MEMO: Renderのダッシュボード側からも設定できるが、明示的に示す
    autoDeploy: false # MEMO: Renderのダッシュボード側からも設定できるが、明示的に示す
